environment:
  CODECOV_TOKEN:
    secure: 6lFWB3pCBPt5kSn3Qezn/EjRyFXkYBnNnVmC9s4m2INZ+GW3jm1TWBNtxaGh/GxR
  PYTHONIOENCODING: utf-8

  matrix:
    - PYTHON: C:\Python27
    - PYTHON: C:\Python27-x64
    - PYTHON: C:\Python33
    - PYTHON: C:\Python33-x64
    - PYTHON: C:\Python34
    - PYTHON: C:\Python34-x64

init:
  - IF DEFINED PYTHON set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

install:
  - ps: Start-FileDownload https://raw.github.com/pypa/pip/master/contrib/get-pip.py
  - python get-pip.py
  - ps: pip install $(python -c 'import setup; print(setup.REQUIRES_PIP)')
  - pip install robpol86-codecov

build_script:
  - ps: mv .git ..
  - pip install .
  - ps: mv ..\.git .

test_script:
  - python setup.py test

after_test: codecov
